### ISSUE TITLE
요구사항 2. 호버 기능 구현

### ISSUE THREAD

**Issue by merrybmc** [wanted-pre-onboarding-internship-1team/pre-onboarding-9th-3-1#2]
- 특정 데이터 구역에 마우스 호버시 id, value_area, value_bar 데이터를 툴팁 형태로 제공해주세요

**Comment by rladygks329** [comment]
해당 작업은 라이브러리에 내장된 경우가 많고, issue 1,3에 비해 크기가 작아 issue 1에 합쳐졌습니다
