### ISSUE TITLE
요구사항 3. 필터링 기능 구현

### ISSUE THREAD

**Issue by merrybmc** [wanted-pre-onboarding-internship-1team/pre-onboarding-9th-3-1#3]
- 필터링 기능을 구현해주세요, 필터링은 특정 데이터를 하이라이트 하는 방식으로 구현해주세요
- 필터링 기능은 버튼 형태로 ID값(지역이름)을 이용해주세요
- 필터링 시 버튼에서 선택한 ID값과 동일한 ID값을 가진 데이터 구역만 하이라이트 처리를 해주세요
- 특정 데이터 구역을 클릭 시에도 필터링 기능과 동일한 형태로 동일한 ID값을 가진 데이터 구역을 하이라이트해주세요

**Comment by rladygks329** [comment]
관심사 분리 로직,  annotation등, best practice에 다양한 의견들이 나왔었고
https://talented-palm-5dd.notion.site/1-48d83304b94c42ad8352fcf6e7973b9f
노션에 정리를 해두었습니다. (3/16 best practice 3)

최종적으로 수정님의 코드가 채택되었습니다.
